In [ ]:
import numpy as np
import pandas as pd

In [23]:
df = pd.read_excel('/Gruppy_22__1.xlsx')

df = df.rename(columns={
        'Часы сна':'hours_sleep',
        'Трудоустройство' : 'placement',
        'Вес' :'weight',
        'Рост' :'height',
        'Расстояние до МИРЭА в часах' :'hours_road_to_mirea',
        'Родители (мама, папа) что пьют' : 'parents',
        'К/Ч' : 'result',
    })

print(df)

    hours_sleep  placement  weight  height  hours_road_to_mirea parents result
0             5          0      90     175             2.000000      кк      ч
1             5          1      82     172             0.800000      кч      ч
2             7          1      75     177             1.000000      кч      к
3            10          0      69     179             0.250000      чч      ч
4             5          1     100     180             2.000000      чч      ч
5             8          0      67     170             2.000000      кк      ч
6             6          1      65     179             1.500000      кч      к
7             8          0      88     187             0.170000      кк      ч
8             6          0     103     184             1.000000      чч      ч
9             8          1      85     195             0.666667      кк      к
10            7          0      62     170             1.000000      чч      ч
11            7          0      70     175             1.000000      кк      к
12            7          0      55     168             1.000000      кк      к
13            7          1      65     178             1.000000      чч      ч
14            8          0      82     190             1.500000      кк      к
15            6          1      51     150             1.500000      чч      к
16            3          1      82     176             1.500000      кк      ч
17            5          0      70     177             1.000000      кк      к
18            9          0      67     172             1.500000      чч      к

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [24]:
first_parent, second_parent, result = [],[],[]

for tup in df.itertuples():
    first_parent.append(10 if tup.parents[0] == 'к' else 0) 
    second_parent.append(10 if tup.parents[1] == 'к' else 0)
    result.append(10 if tup.result == 'к' else 0)
    
df['first_parent'] = first_parent
df['second_parent'] = second_parent
df['result'] = result
df = df.drop(columns=['parents'])

**Важной составляющей метода является нормализация. Разные атрибуты обычно обладают разным диапазоном представленных значений в выборке.**

In [25]:
df['weight'] = df['weight'] / 10
df['height'] = df['height'] / 10
df['hours_road_to_mirea'] = df['hours_road_to_mirea'] * 5
df['placement'] = df['placement'] * 10
df

,hours_sleep,placement,weight,height,hours_road_to_mirea,result,first_parent,second_parent
0,5,0,9.0,17.5,10.000000,0,10,10
1,5,10,8.2,17.2,4.000000,0,10,0
2,7,10,7.5,17.7,5.000000,10,10,0
3,10,0,6.9,17.9,1.250000,0,0,0
4,5,10,10.0,18.0,10.000000,0,0,0
5,8,0,6.7,17.0,10.000000,0,10,10
6,6,10,6.5,17.9,7.500000,10,10,0
7,8,0,8.8,18.7,0.850000,0,10,10
8,6,0,10.3,18.4,5.000000,0,0,0
9,8,10,8.5,19.5,3.333333,10,10,10
10,7,0,6.2,17.0,5.000000,0,0,0
11,7,0,7.0,17.5,5.000000,10,10,10
12,7,0,5.5,16.8,5.000000,10,10,10
13,7,10,6.5,17.8,5.000000,0,0,0
14,8,0,8.2,19.0,7.500000,10,10,10
15,6,10,5.1,15.0,7.500000,10,0,0
16,3,10,8.2,17.6,7.500000,0,10,10
17,5,0,7.0,17.7,5.000000,10,10,10
18,9,0,6.7,17.2,7.500000,10,0,0

In [ ]:
X = []

for tup in df.itertuples():
    X.append([
        tup.hours_sleep,
        tup.placement,
        tup.weight,
        tup.height,
        tup.hours_road_to_mirea,
        tup.first_parent,
        tup.second_parent
    ])
    
y = df['result'].to_list()

In [39]:
class KSR:
    def __init__(self, datasets, labels):
        self.datasets = datasets
        self.labels = labels
            
    def calc_proximity (self, firstObject : list, secondObject : list) -> float:
        if len(firstObject) != len(secondObject):
            raise ValueError('ERROR')
        else:
            return ( sum( (item[0] - item[1]) ** 2 for item in zip(firstObject, secondObject) ) ** 0.5 ) 
    
    def calc_class (self, data:list, k:int) -> int:
        if len(data) == 0:
            raise ValueError('ERROR')
        else:
            proxDataset = sorted( zip([ self.calc_proximity(data, dataset) for dataset in self.datasets ],  self.labels), key=lambda x: x[0])[:k]
            res = sum([item[1] for item in proxDataset]) / (k * 10)
            return 0 if res < 0.5 else 10

In [40]:
KSR(X, y).calc_class(X[11], 3)

10